#!/bin/bash
# Changement de domaine ou de chemin — paquet YunoHost Médiathèque

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Mise à jour de l’URL de ${app}…"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
